### ISSUE TITLE
Сборка клиента 

### ISSUE THREAD

**Issue by a-f0x** [saptan/AuthApp#6]
При сборке клиента, в пакадж не подтягиваются либы. 
Приложение не может найти log4j и падает.

**Comment by saptan** [comment]
Не могу воспроизвести данную ошибку. 
Выполняю команды
`git clone https://github.com/saptan/AuthApp.git`
`cd AuthApp`
`mvn package`

Сборка выполняется в штатном режиме.

**Comment by a-f0x** [comment]
а ты джарник запусти :)

**Comment by saptan** [comment]
Ну если ты запускаешь джарник
`java -jar client-1.0-SNAPSHOT.jar`

И видишь такую ошибку:
```
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at App.<clinit>(App.java:9)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
Exception in thread "main"
```
То это проблема в том, что log4j добавлен в качестве зависимости в pom.xml корневого модуля, а в модуле client при сборке он не подтягивается и потому выдападает такая ошибка при запуске jar файла.
